---
apiVersion: v1 
kind: Service 
metadata:
  name: phpfpm
  labels:
    app: phpfpm
    layer: backend
        
spec:
  type: ClusterIP
  selector:
    app: phpfpm

  ports:
    - port: 9000
      targetPort: 9000
